name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
       python-version: '3.10'
   
    
    - name: bump project version
      run: export VERSION=$(python3 my-app/bumpver.py my-app/pom.xml)
    
    - name: build and upload docker image
      uses: zenato/docker-action@v1.0.0
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
         repository: aviv27400/maven-hello-world
         tag: my-app:$VERSION
      

