name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
       python-version: '3.10'
    
    - name: bump project version
      run: VERSION=$(python3 my-app/bumpver.py)
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -f my-app/Dockerfile -t my-app:$VERSION --build-arg VERSION=$VERSION .

