name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
       python-version: '3.10'
   
    
    - name: bump project version
      run: |
        VERSION=$(python3 my-app/bumpver.py my-app/pom.xml)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Test Version env
      run: echo ${{ env.VERSION }}
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        build-args: VERSION=${{ env.VERSION }}
        tags: aviv27400/maven-hello-world:${{ env.VERSION }}, aviv27400/maven-hello-world:latest
        file: my-app/Dockerfile
        context: my-app/.
        push: true

      

